import {buildSolamiUrl,normalizeSolami,syntheticLog} from '@/lib/solami-blur';
const DEFAULT_WS=['wss://api.mainnet-beta.solana.com','wss://solana-rpc.publicnode.com'];
const RPC_WS_URLS=(process.env.SOLANA_WS_URLS||process.env.SOLANA_WS_URL||'').split(',').map(x=>x.trim()).filter(Boolean);
const WS_URLS=RPC_WS_URLS.length?RPC_WS_URLS:DEFAULT_WS; const SOLAMI_KEY=process.env.SOLAMI_API_KEY||'';
const SOLAMI_URL=buildSolamiUrl(process.env.SOLAMI_DATA_WS_URL||'wss://ws.solami.dev/data/subscribe?chain=solana',SOLAMI_KEY); const USE_SOLAMI=!!SOLAMI_KEY;
const PROGRAMS=['6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P','pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA'];
export const runtime='edge'; export const dynamic='force-dynamic';
export async function GET(request:Request){if(request.headers.get('upgrade')?.toLowerCase()!=='websocket')return new Response('Expected WebSocket',{status:426});const [client,server]=Object.values(new WebSocketPair());server.accept();let closed=false,remote:WebSocket|null=null,reconnectTimer:any=null,reconnectDelay=1000,providerIndex=0,reconnecting=false,events=0,lastEventAt=0,healthTimer:any=null;
const providers=USE_SOLAMI?[SOLAMI_URL,...WS_URLS]:WS_URLS;const source=(i:number)=>USE_SOLAMI&&i===0?'solami-blur':'solana-pubsub';
const send=(x:any)=>{if(!closed)try{server.send(JSON.stringify(x))}catch{}};const closeRemote=()=>{try{remote?.close(1000,'reconnect')}catch{};remote=null};
const shutdown=(code:number,reason:string)=>{if(closed)return;closed=true;if(reconnectTimer)clearTimeout(reconnectTimer);if(healthTimer)clearInterval(healthTimer);closeRemote();try{server.close(code,reason)}catch{}};
const fail=(reason:string)=>{if(closed||reconnecting)return;reconnecting=true;providerIndex=(providerIndex+1)%providers.length;closeRemote();const delay=Math.min(30000,reconnectDelay);reconnectDelay=Math.min(30000,reconnectDelay*2);send({type:'upstream',state:'reconnecting',reason,source:source(providerIndex),events,lastEventAt:lastEventAt||null,delay,ts:Date.now()});reconnectTimer=setTimeout(async()=>{reconnectTimer=null;reconnecting=false;const ok=await connectUpstream();if(!ok)fail('upstream connection failed')},delay)};
const connectUpstream=async():Promise<boolean>=>{if(closed)return false;const url=providers[providerIndex]||providers[0];const solami=USE_SOLAMI&&providerIndex===0;try{const upstream=await fetch(url,{headers:{Upgrade:'websocket',Connection:'Upgrade'}});const ws=upstream.webSocket;if(!ws){fail(`websocket upgrade unavailable: ${source(providerIndex)}`);return false}remote=ws;ws.accept();reconnecting=false;reconnectDelay=1000;events=0;lastEventAt=0;send({type:'upstream',state:'connected',source:source(providerIndex),provider:solami?'solami-blur':url,events:0,lastEventAt:null,ts:Date.now()});ws.addEventListener('message',event=>{if(closed||remote!==ws)return;try{const msg=JSON.parse(String(event.data));if(solami){if(msg?.type==='error'||msg?.error){fail(String(msg?.error?.message||msg?.message||'Solami stream error'));return}const parsed=normalizeSolami(msg);if(parsed){events++;lastEventAt=Date.now();send({type:'event',eventType:parsed.event,source:'solami-blur',events,lastEventAt});send({type:'logs',data:{signature:parsed.signature||undefined,context:{slot:parsed.slot||0},value:{logs:[syntheticLog(parsed)]},solami:parsed}})}return}if(msg.id===1||msg.id===2){if(msg.error){fail(String(msg.error.message||'subscription error'));return}if(msg.result!==undefined)send({type:'subscription',id:msg.id,result:msg.result});return}if(msg.method==='logsNotification'){events++;lastEventAt=Date.now();send({type:'event',eventType:'ONCHAIN_LOG',source:'solana-pubsub',events,lastEventAt});send({type:'logs',data:msg.params})}}catch{}});ws.addEventListener('error',()=>{if(remote===ws)fail(`${source(providerIndex)} upstream error`)});ws.addEventListener('close',()=>{if(remote===ws)fail(`${source(providerIndex)} upstream closed`)});if(solami){for(const filter of [{type:'token_create'},{type:'swap',dex:'pumpswap'},{type:'liquidity',dex:'pumpswap'},{type:'pool_create',dex:'pumpswap'}])try{ws.send(JSON.stringify(filter))}catch{return false}}else try{PROGRAMS.forEach((program,i)=>ws.send(JSON.stringify({jsonrpc:'2.0',id:i+1,method:'logsSubscribe',params:[{mentions:[program]},{commitment:'processed'}]})))}catch{closeRemote();return false}return true};
server.addEventListener('message',(event:any)=>{try{const msg=JSON.parse(String(event.data));if(msg?.type==='ping')send({type:'pong',ts:Date.now(),events,lastEventAt:lastEventAt||null})}catch{}});server.addEventListener('close',()=>shutdown(1000,'client closed'));server.addEventListener('error',()=>shutdown(1011,'client error'));
const ok=await connectUpstream();if(!ok)fail('initial connection failed');send({type:'ready',source:source(providerIndex),providers:providers.length,mode:'event-verified'});healthTimer=setInterval(()=>{if(closed)return;const silent=lastEventAt?Date.now()-lastEventAt:0;send({type:'health',state:lastEventAt&&silent<30000?'LIVE':'CONNECTED_NO_EVENTS',source:source(providerIndex),events,lastEventAt:lastEventAt||null,silentMs:silent||null,ts:Date.now()})},10000);return new Response(null,{status:101,webSocket:client})}