import {buildSolamiUrl,normalizeSolami} from '@/lib/solami-blur';
const DEFAULT_WS=['wss://api.mainnet-beta.solana.com','wss://solana-rpc.publicnode.com'];
const RPC_WS_URLS=(process.env.SOLANA_WS_URLS||process.env.SOLANA_WS_URL||'').split(',').map(x=>x.trim()).filter(Boolean);
const WS_URLS=RPC_WS_URLS.length?RPC_WS_URLS:DEFAULT_WS;
const SOLAMI_KEY=process.env.SOLAMI_API_KEY||'';
const SOLAMI_URL=buildSolamiUrl(process.env.SOLAMI_DATA_WS_URL||'wss://ws.solami.dev/data/subscribe?chain=solana',SOLAMI_KEY);
const USE_SOLAMI=!!SOLAMI_KEY;
const PROGRAMS=['6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P','pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA'];
export const runtime='edge';export const dynamic='force-dynamic';
export async function GET(request:Request){
 if(request.headers.get('upgrade')?.toLowerCase()!=='websocket')return new Response('Expected WebSocket',{status:426});
 const [client,server]=Object.values(new WebSocketPair());server.accept();
 let closed=false,remote:WebSocket|null=null,pingTimer:any=null,reconnectTimer:any=null,reconnecting=false,reconnectDelay=1000,providerIndex=0;
 const providers=USE_SOLAMI?[SOLAMI_URL,...WS_URLS]:WS_URLS;
 const closeRemote=()=>{try{remote?.close(1000,'reconnect')}catch{};remote=null};
 const shutdown=(code:number,reason:string)=>{if(closed)return;closed=true;if(pingTimer)clearInterval(pingTimer);if(reconnectTimer)clearTimeout(reconnectTimer);closeRemote();try{server.close(code,reason)}catch{}};
 const fail=(reason:string)=>{if(closed||reconnecting)return;reconnecting=true;providerIndex=(providerIndex+1)%providers.length;closeRemote();const delay=Math.min(30000,reconnectDelay)*(0.75+Math.random()*0.5);reconnectDelay=Math.min(30000,reconnectDelay*2);try{server.send(JSON.stringify({type:'upstream',state:'reconnecting',reason,source:providerIndex===0&&USE_SOLAMI?'solami-blur':'solana-pubsub',delay:Math.round(delay),ts:Date.now()}))}catch{};reconnectTimer=setTimeout(async()=>{reconnectTimer=null;reconnecting=false;const ok=await connectUpstream();if(!ok)fail('upstream connection failed')},Math.min(30000,Math.max(500,Math.round(delay))))};
 const connectUpstream=async():Promise<boolean>=>{if(closed)return false;const url=providers[providerIndex]||providers[0];const solami=USE_SOLAMI&&providerIndex===0;try{const upstream=await fetch(url,{headers:{Upgrade:'websocket',Connection:'Upgrade'}});const ws=upstream.webSocket;if(!ws){fail(`websocket upgrade unavailable: ${solami?'solami':'solana'}`);return false}remote=ws;ws.accept();reconnecting=false;reconnectDelay=1000;ws.addEventListener('message',event=>{if(closed||remote!==ws)return;try{const msg=JSON.parse(String(event.data));if(solami){const parsed=normalizeSolami(msg);if(parsed)server.send(JSON.stringify({type:'solami',data:parsed}));if(msg?.type==='error'||msg?.error)fail(String(msg?.error?.message||msg?.message||'Solami stream error'));return}if(msg.id===1||msg.id===2){if(msg.error){fail(String(msg.error.message||'subscription error'));return}if(msg.result!==undefined)server.send(JSON.stringify({type:'subscription',id:msg.id,result:msg.result}));return}if(msg.method==='logsNotification')server.send(JSON.stringify({type:'logs',data:msg.params}))}catch{}});ws.addEventListener('error',()=>{if(remote===ws)fail(`${solami?'solami':'solana'} upstream error`)});ws.addEventListener('close',()=>{if(remote===ws)fail(`${solami?'solami':'solana'} upstream closed`)});if(solami){const filters=[{type:'token_create'},{type:'swap',dex:'pumpswap'},{type:'liquidity',dex:'pumpswap'},{type:'pool_create',dex:'pumpswap'}];for(const filter of filters)ws.send(JSON.stringify(filter));server.send(JSON.stringify({type:'upstream',state:'connected',source:'solami-blur',filters:['token_create','swap:pumpswap','liquidity:pumpswap','pool_create:pumpswap'],ts:Date.now()}));return true}try{PROGRAMS.forEach((program,i)=>ws.send(JSON.stringify({jsonrpc:'2.0',id:i+1,method:'logsSubscribe',params:[{mentions:[program]},{commitment:'processed'}]})))}catch{closeRemote();return false}server.send(JSON.stringify({type:'upstream',state:'connected',source:'solana-pubsub',provider:url,ts:Date.now()}));return true};
 server.addEventListener('message',(event:any)=>{if(closed)return;try{const msg=JSON.parse(String(event.data));if(msg?.type==='ping')server.send(JSON.stringify({type:'pong',ts:Date.now()}))}catch{}});server.addEventListener('close',()=>shutdown(1000,'client closed'));server.addEventListener('error',()=>shutdown(1011,'client error'));
 const ok=await connectUpstream();if(!ok)fail('initial connection failed');else server.send(JSON.stringify({type:'ready',source:USE_SOLAMI&&providerIndex===0?'solami-blur':'solana-pubsub',programs:PROGRAMS,commitment:USE_SOLAMI&&providerIndex===0?undefined:'processed',providers:providers.length}));
 pingTimer=setInterval(()=>{if(!closed)try{server.send(JSON.stringify({type:'ping',ts:Date.now()}))}catch{}},15000);
 return new Response(null,{status:101,webSocket:client});
}