'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
type Token={mint:string;symbol:string;ageMs:number;buys:number;sells:number;volumeSol:number;buySol:number;sellSol:number;buyers:number;sellers:number;wallets:number;rotationWallets:number;rotationOrigins:[string,number][];score:number;risk:string;lastSeen:number;graduated?:boolean;priceSol?:number;progress?:number;dex?:{available:boolean;dexId?:string;pairAddress?:string;url?:string;priceUsd?:number;liquidityUsd?:number;volume5m?:number;volume1h?:number;priceChange5m?:number;priceChange1h?:number;marketCap?:number;buys5m?:number;sells5m?:number;boostActive?:number}};
type Event={event?:string;mint?:string;wallet?:string;signature?:string;slot?:number;ts?:number;sol?:number};
const API=(process.env.NEXT_PUBLIC_API_URL||'').replace(/\/$/,'');
const short=(x:string,n=6)=>x?`${x.slice(0,n)}…${x.slice(-4)}`:'—';
const age=(ms:number)=>{const s=Math.max(0,Math.floor(ms/1000));return s<60?`${s}s`:s<3600?`${Math.floor(s/60)}m`:`${Math.floor(s/3600)}h`};
const money=(n?:number)=>n==null?'—':n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(1)}K`:`$${n.toFixed(0)}`;
const pump=(m:string)=>`https://pump.fun/coin/${m}`;const dex=(m:string)=>`https://dexscreener.com/solana/${m}`;
const CREATE='1b72a94ddeeb6376',TRADE='bddb7fd34ee661ee',COMPLETE='5f72619cd42e9808';
function b58(a:Uint8Array){const abc='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const b of a)n=n*256n+BigInt(b);let s='';while(n){s=abc[Number(n%58n)]+s;n/=58n}for(const b of a){if(b)break;s='1'+s}return s||'1'}
function bytes(s:string){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
function u64(a:Uint8Array,o:number){return Number(new DataView(a.buffer,a.byteOffset,a.byteLength).getBigUint64(o,true))}
function i64(a:Uint8Array,o:number){return Number(new DataView(a.buffer,a.byteOffset,a.byteLength).getBigInt64(o,true))}
function u32(a:Uint8Array,o:number){return new DataView(a.buffer,a.byteOffset,a.byteLength).getUint32(o,true)}
function str(a:Uint8Array,o:number){const n=u32(a,o);return[new TextDecoder().decode(a.slice(o+4,o+4+n)),o+4+n]as const}
function decodeLog(log:string,sig:string,slot:number):Event|null{const m=log.match(/^Program data: (.+)$/);if(!m)return null;try{const a=bytes(m[1]);const h=Array.from(a.slice(0,8)).map(x=>x.toString(16).padStart(2,'0')).join('');let o=8;if(h===CREATE){const[name,o1]=str(a,o);o=o1;const[symbol,o2]=str(a,o);o=o2;const[,o3]=str(a,o);o=o3;const mint=b58(a.slice(o,o+32));o+=64;const wallet=b58(a.slice(o,o+32));return{event:'NEW',mint,wallet,signature:sig,slot,ts:Date.now() ,sol:0,symbol:symbol||name}}if(h===TRADE){const mint=b58(a.slice(o,o+32));o+=32;const sol=u64(a,o)/1e9;o+=16;const buy=!!a[o];o++;const wallet=b58(a.slice(o,o+32));o+=32;const et=i64(a,o);return{event:buy?'BUY':'SELL',mint,wallet,signature:sig,slot,ts:et>0?et*1000:Date.now(),buySol:buy?sol:0,sellSol:buy?0:sol,sol}}if(h===COMPLETE)return{event:'GRADUATION',mint:b58(a.slice(8,40)),signature:sig,slot,ts:Date.now()};}catch{}return null}
export default function Home(){
 const [tokens,setTokens]=useState<Token[]>([]),[events,setEvents]=useState<Event[]>([]),[status,setStatus]=useState('CONNECTING'),[tab,setTab]=useState('EARLY'),[min,setMin]=useState(0),[stars,setStars]=useState<Record<string,boolean>>({}),[selected,setSelected]=useState<Token|null>(null),[diag,setDiag]=useState<any>(null);
 const wsRef=useRef<WebSocket|null>(null),reconnectRef=useRef<any>(null),staleRef=useRef<any>(null),backoffRef=useRef(1000),seenRef=useRef<Set<string>>(new Set());
 useEffect(()=>{
  let dead=false;
  const base=API||window.location.origin;
  const wsUrl=base.replace(/^http:/,'ws:').replace(/^https:/,'wss:')+'/api/live/stream';
  const addEvents=(incoming:Event[])=>setEvents(prev=>{const all=[...incoming,...prev];const out:Event[]=[];const seen=new Set<string>();for(const e of all){const k=e.signature||`${e.slot||0}:${e.mint||''}:${e.event||''}:${e.wallet||''}`;if(!seen.has(k)){seen.add(k);out.push(e)}if(out.length>=40)break}return out});
  const hydrate=async()=>{try{const r=await fetch(`${API}/api/live/tokens`,{cache:'no-store'});if(!r.ok)throw new Error('hydrate');const x=await r.json();if(x.source==='solana-mainnet-rpc'){setTokens(Array.isArray(x.tokens)?x.tokens:[]);addEvents(Array.isArray(x.events)?x.events:[]);setDiag(x.diagnostics||null);if(x.degraded)setStatus(s=>s==='LIVE'?'DEGRADED':s)}}catch{}};
  const schedule=()=>{if(dead||reconnectRef.current)return;const delay=Math.min(30000,backoffRef.current)*(0.75+Math.random()*0.5);reconnectRef.current=setTimeout(()=>{reconnectRef.current=null;connect()},delay);backoffRef.current=Math.min(30000,backoffRef.current*2)};
  const connect=()=>{if(dead||wsRef.current)return;setStatus(s=>s==='LIVE'?'RECONNECTING':'CONNECTING');let opened=false;let lastMessage=Date.now();let pingTimer:any=null;try{const ws=new WebSocket(wsUrl);wsRef.current=ws;
   const cleanup=()=>{if(pingTimer)clearInterval(pingTimer);if(staleRef.current){clearTimeout(staleRef.current);staleRef.current=null}};
   const staleCheck=()=>{if(dead||wsRef.current!==ws)return;if(Date.now()-lastMessage>45000){try{ws.close()}catch{};return}staleRef.current=setTimeout(staleCheck,15000)};
   ws.onopen=()=>{opened=true;lastMessage=Date.now();backoffRef.current=1000;setStatus('LIVE');try{ws.send(JSON.stringify({type:'ping',ts:Date.now()}))}catch{};pingTimer=setInterval(()=>{try{ws.send(JSON.stringify({type:'ping',ts:Date.now()}))}catch{}},10000);staleCheck();hydrate()};
   ws.onmessage=e=>{lastMessage=Date.now();try{const msg=JSON.parse(String(e.data));if(msg.type==='ping'){try{ws.send(JSON.stringify({type:'pong',ts:Date.now()}))}catch{};return}if(msg.type==='pong'||msg.type==='ready')return;if(msg.type==='logs'){const d=msg.data;const value=d?.value||{};const signature=d?.signature||'';const slot=d?.context?.slot||0;if(signature&&seenRef.current.has(signature))return;if(signature)seenRef.current.add(signature);for(const raw of (value.logs||[])){const parsed=decodeLog(raw,signature,slot);if(parsed)addEvents([parsed]);}setStatus('LIVE');if(seenRef.current.size>5000)seenRef.current=new Set(Array.from(seenRef.current).slice(-2500));}}catch{}};
   ws.onerror=()=>{setStatus(s=>s==='LIVE'?'DEGRADED':s)};ws.onclose=()=>{cleanup();if(wsRef.current===ws)wsRef.current=null;if(!dead){setStatus(opened?'RECONNECTING':'DEGRADED');schedule();}};
  }catch{setStatus('DEGRADED');schedule()}};
  connect();
  const resync=setInterval(hydrate,20000);
  return()=>{dead=true;clearInterval(resync);if(reconnectRef.current)clearTimeout(reconnectRef.current);if(staleRef.current)clearTimeout(staleRef.current);try{wsRef.current?.close(1000,'unmount')}catch{};wsRef.current=null};
 },[]);
 const visible=useMemo(()=>tokens.filter(t=>t.score>=min).filter(t=>tab==='ALL'||tab==='EARLY'&&t.ageMs<15*60e3||tab==='HOT'&&t.buySol>t.sellSol*1.5||tab==='WHALES'&&t.volumeSol>2||tab==='ROTATION'&&t.rotationWallets>0).sort((a,b)=>b.score-a.score),[tokens,min,tab]);
 const starred=Object.values(stars).filter(Boolean).length;
 return <main><header className="topbar terminal-grid"><div className="brand"><div className="brandmark">⌁</div><div><div className="eyebrow">LIQUIDITY INTELLIGENCE // STAMPEDE FUSION</div><h1>ON-CHAIN EARLY RADAR <span>LIVE</span></h1></div></div><div className="live-status"><i className={status==='LIVE'?'liveDot':''}/> {status} · SOLANA MAINNET</div></header>
 <section className="marketbar terminal-grid"><div className="market"><span className="coin sol">SOL</span><div><small>NETWORK</small><strong>MAINNET</strong></div><span className="up">● STREAM</span></div><div className="market"><div><small>PUMP.FUN PROGRAM</small><strong>6EF8rrect…</strong></div><span className="up">ON-CHAIN</span></div><div className="market"><div><small>MARKET ENRICHMENT</small><strong>DEXSCREENER</strong></div><span className="up">LIVE</span></div><div className="market"><div><small>DATA MODE</small><strong>LIVE ONLY</strong></div><span className="up">NO MOCK</span></div></section>
 <section className="stats"><Stat t="LIVE TOKENS" v={String(tokens.length)}/><Stat t="ROTATION SIGNALS" v={String(tokens.filter(x=>x.rotationWallets>0).length)}/><Stat t="DEX PAIRS" v={String(tokens.filter(x=>x.dex?.available).length)}/><Stat t="STARRED" v={String(starred)}/></section>
 <section className="heroGrid"><section className="card sniper"><div className="sniperhead"><div><span>STAMPEDE × PUMP.FUN × DEXSCREENER</span><h2>EARLY-LAUNCH RADAR</h2><p>On-chain launch flow enriched with live DEX price, liquidity, volume and market data. Rotation is observed sell → buy behavior, not proof of causality.</p></div><div className="radar"><b>● {status}</b><strong>{visible.length}</strong><small>CANDIDATES</small></div></div><div className="scanner-tabs">{(['EARLY','ALL','HOT','WHALES','ROTATION'] as const).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}<label>MIN SCORE <input type="range" min="0" max="100" value={min} onChange={e=>setMin(+e.target.value)}/><b>{min}</b></label></div><div className="tablehead"><span>★ TOKEN</span><span>AGE</span><span>PRICE / LIQ</span><span>VOL 5M</span><span>B/S</span><span>ROT</span><span>SCORE</span><span>EXT</span></div>{visible.map(t=><div className={`sniperrow ${t.score>=80?'elite':''}`} key={t.mint} onClick={()=>setSelected(t)}><button className={`star ${stars[t.mint]?'on':''}`} onClick={e=>{e.stopPropagation();setStars(s=>({...s,[t.mint]:!s[t.mint]}))}}>{stars[t.mint]?'★':'☆'}</button><div><b>{t.symbol}</b><small>{short(t.mint,8)} {t.dex?.dexId?`· ${t.dex.dexId}`:''}</small></div><span className="age">{age(t.ageMs)}</span><span><b>{t.dex?.priceUsd!=null?`$${t.dex.priceUsd.toFixed(t.dex.priceUsd<.01?8:4)}`:`${t.priceSol.toFixed(6)} SOL`}</b><small>{money(t.dex?.liquidityUsd)} liq</small></span><span>{money(t.dex?.volume5m)}</span><span className={t.buySol>=t.sellSol?'green':'red'}>{t.dex?.buys5m??t.buyers}/{t.dex?.sells5m??t.sellers}</span><span className="cyan">{t.rotationWallets}</span><strong>{t.score}</strong><div className="links"><a href={pump(t.mint)} target="_blank">PUMP</a><a href={t.dex?.url||dex(t.mint)} target="_blank">DEX</a></div></div>)}{!visible.length&&<Empty status={status}/>}<div className="diagnostic">WS PRIMARY · resync 20s · RPC {diag?.transactions??0}/{diag?.usable??0} tx · decoded {diag?.decodedEvents??0} events · {diag?.rpcErrors??0} RPC errors</div></section>
 <section className="card flowcard"><div className="section-head"><div><span>STAMPEDE ENGINE</span><h2>WALLET ROTATION FLOW</h2></div><b className="stream">● LIVE</b></div><Flow tokens={visible.slice(0,6)} onSelect={setSelected}/><div className="flowLegend"><span>ORIGIN</span><span>ROTATING WALLETS</span><span>TARGET</span></div></section></section>
 <section className="lowerGrid"><section className="card pumpfeed"><div className="section-head"><div><span>SOLANA // PUMP.FUN</span><h2>LIVE EVENT STREAM</h2></div></div>{events.slice(0,18).map((e,i)=><div className="liveevent" key={`${e.signature||'e'}-${e.slot||0}-${i}`}><b className={`event-kind ${(e.event||'').toLowerCase()}`}>{e.event||'EVENT'}</b><code>{short(e.signature||'',10)}</code><span>{e.mint?short(e.mint,7):'—'}</span><small>{e.wallet?short(e.wallet,6):`slot ${e.slot??'—'}`}</small></div>)}{!events.length&&<Empty status={status}/>}</section><section className="card smart"><div className="section-head"><div><span>DEXSCREENER ENRICHMENT</span><h2>MARKET LIQUIDITY BOARD</h2></div></div>{visible.filter(t=>t.dex?.available).slice(0,8).map(t=><div className="rotation" key={t.mint}><div><b>{t.symbol}</b><small>{t.dex?.dexId||'DEX'} · {short(t.dex?.pairAddress||'',7)}</small></div><strong>{money(t.dex?.liquidityUsd)}</strong><div className="bar"><i style={{width:`${Math.min(100,(t.dex?.liquidityUsd||0)/1000)}%`}}/></div><span>{money(t.dex?.volume5m)} 5M · {t.dex?.priceChange5m!=null?`${t.dex.priceChange5m.toFixed(1)}%`:''}</span></div>)}{!visible.some(t=>t.dex?.available)&&<Empty status="WAITING FOR DEXSCREENER PAIR"/>}</section></section>
 <section className="card matrix"><div className="section-title"><div><span>DECISION ENGINE</span><h2>REAL-TIME CONFLUENCE</h2></div><small>on-chain + wallet rotation + DEX liquidity + DEX velocity</small></div><div className="confluence"><Metric l="FRESHNESS" v={visible[0]?age(visible[0].ageMs):'—'}/><Metric l="BUY FLOW" v={visible[0]?`${Math.round(visible[0].buySol/Math.max(.0001,visible[0].buySol+visible[0].sellSol)*100)}%`:'—'}/><Metric l="LIQUIDITY" v={visible[0]?money(visible[0].dex?.liquidityUsd):'—'}/><Metric l="VOL 5M" v={visible[0]?money(visible[0].dex?.volume5m):'—'}/><Metric l="ROTATION" v={visible[0]?String(visible[0].rotationWallets):'—'}/><Metric l="RISK" v={visible[0]?.risk||'—'}/></div></section>
 <footer className="ticker">LIVE ON-CHAIN · PUMP.FUN · DEXSCREENER · WALLET ROTATION · STAMPEDE RADAR · NO MOCK DATA · NO AUTOMATIC EXECUTION</footer>
 {selected&&<aside className="drawer"><button className="close" onClick={()=>setSelected(null)}>×</button><span>TOKEN INTELLIGENCE</span><h2>{selected.symbol}</h2><code>{selected.mint}</code><div className="drawerScore"><strong>{selected.score}</strong><small>SCORE</small></div><div className="drawerGrid"><Metric l="AGE" v={age(selected.ageMs)}/><Metric l="PRICE USD" v={selected.dex?.priceUsd!=null?`$${selected.dex.priceUsd}`:'—'}/><Metric l="LIQUIDITY" v={money(selected.dex?.liquidityUsd)}/><Metric l="VOL 5M" v={money(selected.dex?.volume5m)}/><Metric l="VOL 1H" v={money(selected.dex?.volume1h)}/><Metric l="MCAP" v={money(selected.dex?.marketCap)}/><Metric l="ROTATION" v={String(selected.rotationWallets)}/><Metric l="RISK" v={selected.risk}/><Metric l="BONDING" v={`${Math.round(selected.progress||0)}%`}/><Metric l="PRICE SOL" v={`${(selected.priceSol||0).toFixed(9)} SOL`}/></div><h3>ROTATION ORIGINS</h3>{selected.rotationOrigins.length?selected.rotationOrigins.map(([m,n])=><div className="origin" key={m}><span>{short(m,10)}</span><b>{n} wallets</b></div>):<Empty status="NO OBSERVED ROTATION YET"/>}<div className="drawerLinks"><a href={pump(selected.mint)} target="_blank">PUMP.FUN</a><a href={selected.dex?.url||dex(selected.mint)} target="_blank">DEXSCREENER</a><button onClick={()=>navigator.clipboard?.writeText(selected.mint)}>COPY CA</button></div></aside>}
 </main>}
function Stat({t,v}:{t:string;v:string}){return <div className="stat card"><span>{t}</span><strong>{v}</strong></div>};function Metric({l,v}:{l:string;v:string}){return <div className="metric"><span>{l}</span><strong>{v}</strong></div>};function Empty({status}:{status:string}){return <div className="empty">{status==='LIVE'?'WAITING FOR LIVE CHAIN DATA…':status}</div>};
function Flow({tokens,onSelect}:{tokens:Token[];onSelect:(t:Token)=>void}){if(!tokens.length)return <Empty status="WAITING FOR ROTATION DATA"/>;return <div className="flowGraph"><svg viewBox="0 0 700 300" preserveAspectRatio="xMidYMid meet"><defs><filter id="glow"><feGaussianBlur stdDeviation="3" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>{tokens.map((t,i)=>{const y=45+i*40;const x1=55,x2=350,x3=640;return <g key={t.mint}><path d={`M ${x1} ${y} C 180 ${y}, 210 150, ${x2} 150 C 490 150, 520 ${y}, ${x3} ${y}`} className="flowline"/><text x={x1} y={y-7} className="svgText">{short(t.rotationOrigins[0]?.[0]||'NO ORIGIN',5)}</text><circle cx={x2} cy="150" r={24} className="target" onClick={()=>onSelect(t)}/><text x={x2} y="154" textAnchor="middle" className="targetText">{t.score}</text><text x={x3} y={y-7} className="svgText">{short(t.mint,5)}</text></g>})}</svg></div>}
