export type SolamiEvent={event:string;mint?:string;wallet?:string;signature?:string;slot?:number;ts:number;sol?:number;symbol?:string;source:'solami-blur';rawType:string};
const pick=(o:any,...keys:string[])=>{for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return undefined};
export function buildSolamiUrl(base:string,key:string){try{const u=new URL(base);if(key&&!u.searchParams.has('api_key'))u.searchParams.set('api_key',key);return u.toString()}catch{return base}}
export function normalizeSolami(raw:any):SolamiEvent|null{const d=raw?.data&&typeof raw.data==='object'?raw.data:raw;const type=String(pick(raw,'type')||pick(d,'type')||'').toLowerCase();const mint=pick(d,'mint','token_address','tokenAddress','base_token_address','baseTokenAddress');if(!mint)return null;const wallet=pick(d,'wallet','user','trader','owner','maker','user_address');const signature=pick(d,'signature','tx_signature','txSignature','transaction','transaction_signature');const slot=Number(pick(d,'slot','block_slot','blockSlot')||0);const rawTs=pick(d,'timestamp','block_time','blockTime','ts','time');const ts=typeof rawTs==='number'?(rawTs<1e12?rawTs*1000:rawTs):Date.now();let event='';if(type==='token_create'||type==='token_created'||type==='launch'||type==='token_launch')event='NEW';else if(type==='swap'||type==='trade'){const side=String(pick(d,'side','direction')||'').toLowerCase();event=side==='sell'||d?.is_buy===false?'SELL':'BUY'}else if(type==='pool_create'||type==='pool_created')event='POOL';else if(type==='liquidity')event='LIQUIDITY';else if(type==='complete'||type==='graduation'||type==='graduated')event='GRADUATION';if(!event)return null;const solRaw=pick(d,'volume_sol','sol_amount','solAmount','amount_sol','amountSol');return{event,mint,wallet,signature,slot,ts,sol:solRaw==null?undefined:Number(solRaw),symbol:pick(d,'symbol','token_symbol','tokenSymbol'),source:'solami-blur',rawType:type}}
function b58bytes(s:string){const abc='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const c of s){const i=abc.indexOf(c);if(i<0)return null;n=n*58n+BigInt(i)}const out:number[]=[];while(n){out.unshift(Number(n&255n));n>>=8n}for(let i=0;i<s.length&&s[i]==='1';i++)out.unshift(0);return out.length===32?Uint8Array.from(out):null}
function putU64(a:number[],n:number){let x=BigInt(Math.max(0,Math.round(n)));for(let i=0;i<8;i++){a.push(Number(x&255n));x>>=8n}}
function putI64(a:number[],n:number){let x=BigInt(Math.round(n));if(x<0)x=(1n<<64n)+x;for(let i=0;i<8;i++){a.push(Number(x&255n));x>>=8n}}
function b64(a:number[]){let s='';for(const x of a)s+=String.fromCharCode(x);return btoa(s)}
export function syntheticLog(e:SolamiEvent){const mint=b58bytes(String(e.mint||''))||new Uint8Array(32);const wallet=b58bytes(String(e.wallet||''))||new Uint8Array(32);const head=e.event==='NEW'?'1b72a94ddeeb6376':e.event==='GRADUATION'?'5f72619cd42e9808':'bddb7fd34ee661ee';const a:number[]=Array.from(new Uint8Array(head.match(/../g)!.map(x=>parseInt(x,16))));if(e.event==='NEW'){const name=String(e.symbol||'TOKEN'),put=(v:string)=>{const b=new TextEncoder().encode(v);a.push(b.length&255,(b.length>>8)&255,(b.length>>16)&255,(b.length>>24)&255,...Array.from(b))};put(name);put(name);put('');a.push(...mint,...new Uint8Array(32),...wallet)}else if(e.event==='GRADUATION'){a.push(...mint)}else{a.push(...mint);putU64(a,(e.sol||0)*1e9);putU64(a,0);a.push(e.event==='BUY'?1:0,...wallet);putI64(a,(e.ts||Date.now())/1000);a.push(...new Uint8Array(32));}return`Program data: ${b64(a)}`}
