const PUMP='6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P';
const RPCS=(process.env.SOLANA_RPC_URL||'').split(',').map(x=>x.trim()).filter(Boolean);
const RPC_URLS=Array.from(new Set([...RPCS,...(process.env.HELIUS_API_KEY?[`https://mainnet.helius-rpc.com/?api-key=${process.env.HELIUS_API_KEY}`]:[]),...(process.env.ALCHEMY_API_KEY?[`https://solana-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`]:[]),'https://solana-rpc.publicnode.com']));
const DEX='https://api.dexscreener.com';
type E={event:string;mint?:string;wallet?:string;signature:string;slot:number;ts:number;sol?:number;symbol?:string;reserves?:{virtualSol:number;virtualToken:number;realSol:number;realToken:number}};
type Pair={dexId?:string;url?:string;pairAddress?:string;baseToken?:{address:string;name?:string;symbol?:string};priceUsd?:string|null;txns?:Record<string,{buys?:number;sells?:number}>;volume?:Record<string,number>;priceChange?:Record<string,number>;liquidity?:{usd?:number;base?:number;quote?:number};fdv?:number|null;marketCap?:number|null;boosts?:{active?:number}};
const CREATE='1b72a94ddeeb6376',TRADE='bddb7fd34ee661ee',COMPLETE='5f72619cd42e9808';
function b58(a:Uint8Array){const abc='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const b of a)n=n*256n+BigInt(b);let s='';while(n){s=abc[Number(n%58n)]+s;n/=58n}for(const b of a){if(b)break;s='1'+s}return s||'1'}
function bytes(s:string){const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
function u64(a:Uint8Array,o:number){return Number(new DataView(a.buffer,a.byteOffset,a.byteLength).getBigUint64(o,true))}
function i64(a:Uint8Array,o:number){return Number(new DataView(a.buffer,a.byteOffset,a.byteLength).getBigInt64(o,true))}
function u32(a:Uint8Array,o:number){return new DataView(a.buffer,a.byteOffset,a.byteLength).getUint32(o,true)}
function str(a:Uint8Array,o:number){const n=u32(a,o);return[new TextDecoder().decode(a.slice(o+4,o+4+n)),o+4+n]as const}
function decode(log:string,sig:string,slot:number,ts:number):E|null{const m=log.match(/^Program data:\s*(.+)$/);if(!m)return null;try{const a=bytes(m[1].trim());if(a.length<8)return null;const h=Array.from(a.slice(0,8)).map(x=>x.toString(16).padStart(2,'0')).join('');let o=8;if(h===CREATE){const[name,o1]=str(a,o);o=o1;const[symbol,o2]=str(a,o);o=o2;const[,o3]=str(a,o);o=o3;if(o+96>a.length)return null;const mint=b58(a.slice(o,o+32));o+=64;const user=b58(a.slice(o,o+32));return{event:'NEW',mint,wallet:user,signature:sig,slot,ts,symbol:symbol||name}}if(h===TRADE){if(o+32+8+8+1+32+8+8+8+8>a.length)return null;const mint=b58(a.slice(o,o+32));o+=32;const sol=u64(a,o)/1e9;o+=8;o+=8;const buy=!!a[o];o++;const wallet=b58(a.slice(o,o+32));o+=32;const et=i64(a,o);o+=8;const virtualSol=u64(a,o)/1e9;o+=8;const virtualToken=u64(a,o);o+=8;const realSol=u64(a,o)/1e9;o+=8;const realToken=u64(a,o);return{event:buy?'BUY':'SELL',mint,wallet,signature:sig,slot,ts:et>0?et*1000:ts,sol,reserves:{virtualSol,virtualToken,realSol,realToken}}}if(h===COMPLETE&&a.length>=40)return{event:'GRADUATION',mint:b58(a.slice(8,40)),signature:sig,slot,ts}}catch{}return null}
async function post(url:string,body:any){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),cache:'no-store'});if(!r.ok)throw Error(`RPC ${r.status}`);return r.json()}
let active=0;
async function rpc(method:string,params:any[]){for(let n=0;n<RPC_URLS.length;n++){const i=(active+n)%RPC_URLS.length;try{const j=await post(RPC_URLS[i],{jsonrpc:'2.0',id:Date.now(),method,params});if(j.error)throw Error(j.error.message||'RPC error');active=i;return j.result}catch{}}throw Error('All RPC providers unavailable')}
async function batch(reqs:any[]){for(let n=0;n<RPC_URLS.length;n++){const i=(active+n)%RPC_URLS.length;try{const j=await post(RPC_URLS[i],reqs.map((x,k)=>({...x,id:k+1})));if(!Array.isArray(j))throw Error('RPC batch invalid');active=i;return j}catch{}}throw Error('All RPC providers unavailable')}
let pairCache=new Map<string,Pair>(),pairAt=0;
async function dex(mints:string[]){if(Date.now()-pairAt<5000&&pairCache.size)return pairCache;const out=new Map<string,Pair>();for(let i=0;i<mints.length;i+=30)try{const r=await fetch(`${DEX}/tokens/v1/solana/${mints.slice(i,i+30).join(',')}`,{cache:'no-store'});if(!r.ok)continue;const ps=await r.json() as Pair[];for(const p of Array.isArray(ps)?ps:[]){const m=p.baseToken?.address;if(!m)continue;const s=(p.liquidity?.usd||0)+(p.volume?.h24||0)*.05,old=out.get(m),os=(old?.liquidity?.usd||0)+(old?.volume?.h24||0)*.05;if(!old||s>os)out.set(m,p)}}catch{}if(out.size){pairCache=out;pairAt=Date.now()}return pairCache}
export const dynamic='force-dynamic';export const runtime='edge';
let cache:any=null,lastAt=0;
export async function GET(){const now=Date.now();if(cache&&now-lastAt<1000)return Response.json({...cache,generatedAt:now},{headers:{'cache-control':'no-store'}});try{const sigs=await rpc('getSignaturesForAddress',[PUMP,{limit:100,commitment:'confirmed'}]) as any[];const usable=sigs.filter(s=>!s.err).slice(0,60);const replies=await batch(usable.map(s=>({jsonrpc:'2.0',method:'getTransaction',params:[s.signature,{encoding:'json',commitment:'confirmed',maxSupportedTransactionVersion:0}]})));const es:E[]=[];for(let i=0;i<usable.length;i++){const tx=replies[i]?.result;if(!tx?.meta?.logMessages)continue;for(const l of tx.meta.logMessages as string[]){const e=decode(l,usable[i].signature,tx.slot,(tx.blockTime||0)*1000||now);if(e)es.push(e)}}const by=new Map<string,any>();for(const e of es){if(!e.mint)continue;let t=by.get(e.mint);if(!t){t={mint:e.mint,symbol:e.symbol||e.mint.slice(0,6),createdAt:0,lastSeen:e.ts,buys:0,sells:0,buySol:0,sellSol:0,buyers:new Set<string>(),sellers:new Set<string>(),wallets:new Set<string>(),graduated:false,reserves:e.reserves};by.set(e.mint,t)}t.lastSeen=Math.max(t.lastSeen,e.ts);if(e.symbol)t.symbol=e.symbol;if(e.event==='NEW')t.createdAt=t.createdAt?Math.min(t.createdAt,e.ts):e.ts;if(e.event==='GRADUATION')t.graduated=true;if(e.reserves)t.reserves=e.reserves;if(e.event==='BUY'){t.buys++;t.buySol+=e.sol||0;if(e.wallet){t.buyers.add(e.wallet);t.wallets.add(e.wallet)}}if(e.event==='SELL'){t.sells++;t.sellSol+=e.sol||0;if(e.wallet){t.sellers.add(e.wallet);t.wallets.add(e.wallet)}}}
const acts=es.filter(e=>(e.event==='BUY'||e.event==='SELL')&&e.wallet).sort((a,b)=>a.ts-b.ts),rots=new Map<string,Map<string,number>>();for(let i=0;i<acts.length;i++){const a=acts[i];if(a.event!=='SELL')continue;for(let j=i+1;j<acts.length;j++){const b=acts[j];if(b.ts-a.ts>300000)break;if(b.wallet===a.wallet&&b.event==='BUY'&&b.mint&&b.mint!==a.mint){const m=rots.get(b.mint)||new Map<string,number>();m.set(a.mint,(m.get(a.mint)||0)+1);rots.set(b.mint,m);break}}}
const pairs=await dex([...by.keys()].slice(0,60)),tokens:any[]=[];for(const t of by.values()){const vol=t.buySol+t.sellSol,w=t.wallets.size,rot=rots.get(t.mint)||new Map<string,number>(),rc=[...rot.values()].reduce((a,b)=>a+b,0),flow=vol?t.buySol/vol:0,age=t.createdAt?Math.max(0,now-t.createdAt):null,fresh=age===null?0:age<120000?25:age<300000?20:age<900000?12:5,activity=Math.min(25,(t.buys+t.sells)*2),breadth=Math.min(20,w*2),rotationScore=Math.min(10,rc*2),p=pairs.get(t.mint),liq=p?.liquidity?.usd||0,dexBonus=p?Math.min(10,Math.round(Math.log10(1+liq)*2)):0,score=Math.round(Math.min(100,activity+breadth+flow*20+fresh+rotationScore+dexBonus)),hasCreate=age!==null,hasActivity=t.buys+t.sells>0,hasLiquidity=(t.reserves?.realSol||0)>0||liq>0,eligible=hasCreate&&hasActivity&&hasLiquidity&&!t.graduated,star=eligible&&score>=75&&flow>=.6,risk=!eligible?'UNVERIFIED':t.sells>t.buys*1.5?'HIGH':w<3?'UNKNOWN':flow>.6?'LOW':'MEDIUM',r=t.reserves,price=r?.virtualToken?r.virtualSol/r.virtualToken:null,progress=r?.realSol?Math.min(100,r.realSol/85*100):null,tx=p?.txns?.m5;tokens.push({mint:t.mint,symbol:t.symbol,ageMs:age,buys:t.buys,sells:t.sells,volumeSol:+vol.toFixed(4),buySol:+t.buySol.toFixed(4),sellSol:+t.sellSol.toFixed(4),buyers:t.buyers.size,sellers:t.sellers.size,wallets:w,rotationWallets:rc,rotationOrigins:[...rot.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5),score,risk,eligible,star,starReason:star?'verified create + activity + liquidity + positive flow':!hasCreate?'no verified create event':!hasLiquidity?'no observed liquidity':t.graduated?'graduated':'threshold not met',hardGates:{verifiedCreate:hasCreate,activity:hasActivity,liquidity:hasLiquidity,notGraduated:!t.graduated},lastSeen:t.lastSeen,graduated:t.graduated,priceSol:price,progress,dex:p?{available:true,dexId:p.dexId,pairAddress:p.pairAddress,url:p.url,priceUsd:p.priceUsd?+p.priceUsd:undefined,liquidityUsd:liq,volume5m:p.volume?.m5,volume1h:p.volume?.h1,priceChange5m:p.priceChange?.m5,priceChange1h:p.priceChange?.h1,fdv:p.fdv||undefined,marketCap:p.marketCap||undefined,buys5m:tx?.buys,sells5m:tx?.sells,boostActive:p.boosts?.active}:undefined})}
tokens.sort((a,b)=>Number(b.star)-Number(a.star)||b.score-a.score);const payload={tokens:tokens.slice(0,120),events:es.slice(-300).reverse(),source:'solana-mainnet-rpc',dexSource:'dexscreener',degraded:false,diagnostics:{signatures:sigs.length,usable:usable.length,transactions:replies.filter(x=>x?.result).length,rpcErrors:replies.filter(x=>x?.error).length,decodedEvents:es.length,tokens:tokens.length,starred:tokens.filter(t=>t.star).length,latestSignature:sigs[0]?.signature||null,latestSlot:usable[0]?.slot||null,commitment:'confirmed',activeRpc:active+1,rpcProviders:RPC_URLS.length},providerStatus:{solanaRpc:true,dexscreener:true,jupiter:!!process.env.JUPITER_API_KEY,birdeye:!!process.env.BIRDEYE_API_KEY,goplus:!!process.env.GOPLUS_API_KEY,helius:!!process.env.HELIUS_API_KEY,alchemy:!!process.env.ALCHEMY_API_KEY,bitquery:!!process.env.BITQUERY_TOKEN},generatedAt:now};cache=payload;lastAt=now;return Response.json(payload,{headers:{'cache-control':'no-store'}})}catch(err){if(cache)return Response.json({...cache,degraded:true,error:String(err),stale:true,generatedAt:now},{headers:{'cache-control':'no-store'}});return Response.json({tokens:[],events:[],source:'solana-mainnet-rpc',dexSource:'dexscreener',degraded:true,error:String(err),diagnostics:{signatures:0,usable:0,transactions:0,rpcErrors:1,decodedEvents:0,tokens:0,starred:0,latestSlot:null,commitment:'confirmed'},generatedAt:now},{status:200,headers:{'cache-control':'no-store'}})}}